In [4]:
import pandas as pd

path = "C:/Users/rapa/Desktop/빅데이터분석기사실기/covid-vaccination-vs-death_ratio.csv"
df = pd.read_csv(path)
print(df.head())

   Unnamed: 0      country iso_code        date  total_vaccinations  \
0           0  Afghanistan      AFG  2021-05-11            504502.0
1           1  Afghanistan      AFG  2021-05-20            547901.0
2           2  Afghanistan      AFG  2021-05-24            573277.0
3           3  Afghanistan      AFG  2021-05-26            590454.0
4           4  Afghanistan      AFG  2021-05-27            593313.0

   people_vaccinated  people_fully_vaccinated  New_deaths  population  \
0           448878.0                  55624.0          12  40374668.0
1           470341.0                  77560.0          10  40374668.0
2           476367.0                  96910.0          10  40374668.0
3           479372.0                 111082.0          19  40374668.0
4           479574.0                 113739.0          14  40374668.0

      ratio
0  1.111781
1  1.164941
2  1.179866
3  1.187309
4  1.187809

In [7]:
# 마지막 접종률을 기준으로 설정
df2 = df.groupby('country').max() # ** 이부분 공부 필요
print(df2)

                                                    Unnamed: 0 iso_code  \
country
Afghanistan                                                 35      AFG
Albania                                                    219      ALB
Algeria                                                    239      DZA
Andorra                                                    270      AND
Angola                                                     323      AGO
...                                                        ...      ...
Wallis and Futuna                                        32473      WLF
Yemen                                                    32488      YEM
Zambia                                                   32559      ZMB
Zimbabwe                                                 32910      ZWE
occupied Palestinian territory, including east ...       23198      PSE

                                                          date  \
country
Afghanistan                                         2022-03-22
Albania                                             2022-03-24
Algeria                                             2022-03-09
Andorra                                             2022-03-13
Angola                                              2022-03-25
...                                                        ...
Wallis and Futuna                                   2022-03-21
Yemen                                               2022-03-16
Zambia                                              2022-02-27
Zimbabwe                                            2022-03-29
occupied Palestinian territory, including east ...  2022-03-24

                                                    total_vaccinations  \
country
Afghanistan                                                  5751015.0
Albania                                                      2754244.0
Algeria                                                     13704895.0
Andorra                                                       151997.0
Angola                                                      17535411.0
...                                                                ...
Wallis and Futuna                                              12940.0
Yemen                                                         807502.0
Zambia                                                       2822009.0
Zimbabwe                                                     9039729.0
occupied Palestinian territory, including east ...           3694897.0

                                                    people_vaccinated  \
country
Afghanistan                                                 5082824.0
Albania                                                     1278902.0
Algeria                                                     7461932.0
Andorra                                                       57817.0
Angola                                                     11235059.0
...                                                               ...
Wallis and Futuna                                              6483.0
Yemen                                                        643501.0
Zambia                                                      2487149.0
Zimbabwe                                                    5053114.0
occupied Palestinian territory, including east ...          1995873.0

                                                    people_fully_vaccinated  \
country
Afghanistan                                                       4420127.0
Albania                                                           1215199.0
Algeria                                                           6110712.0
Andorra                                                             53367.0
Angola                                                            5993792.0
...                                                                     ...
Wallis and Futuna                                                    6457.0
Yemen                                                              404781.0
Zambia                                                            1862614.0
Zimbabwe                                                          3510256.0
occupied Palestinian territory, including east ...                1756319.0

                                                    New_deaths  population  \
country
Afghanistan                                                 86  40374668.0
Albania                                                     18   2869700.0
Algeria                                                     34  45061896.0
Andorra                                                      2     77355.0
Angola                                                      18  34566172.0
...                                                        ...         ...
Wallis and Futuna                                            2     11094.0
Yemen                                                       10  30882462.0
Zambia                                                      72  19238117.0
Zimbabwe                                                   107  15229891.0
occupied Palestinian territory, including east ...          34   5293440.0

                                                        ratio
country
Afghanistan                                         12.589141
Albania                                             44.565704
Algeria                                             16.559294
Andorra                                             74.742421
Angola                                              32.503047
...                                                       ...
Wallis and Futuna                                   58.436993
Yemen                                                2.083710
Zambia                                              12.928235
Zimbabwe                                            33.178924
occupied Palestinian territory, including east ...  37.704650

[197 rows x 9 columns]

In [9]:
df2 = df2.sort_values(by = 'ratio', ascending = False) # ** 이 부분 암기 필요/ # 오른차순 false
print(df2)

                      Unnamed: 0 iso_code        date  total_vaccinations  \
country
Gibraltar                  11368      GIB  2022-03-24            116358.0
Malta                      19948      MLT  2022-03-28           1255851.0
Niue                       22376      NIU  2022-03-13              4161.0
United Arab Emirates       30916      ARE  2022-03-29          24463702.0
Portugal                   24636      PRT  2022-03-10          22923599.0
...                          ...      ...         ...                 ...
Papua New Guinea           23300      PNG  2022-03-28            574716.0
Yemen                      32488      YEM  2022-03-16            807502.0
Chad                        5884      TCD  2022-03-18            419469.0
Haiti                      12640      HTI  2022-03-23            249801.0
Burundi                     4798      BDI  2022-03-18             12166.0

                      people_vaccinated  people_fully_vaccinated  New_deaths  \
country
Gibraltar                       42034.0                  41228.0           3
Malta                          473639.0                 466296.0           7
Niue                             1650.0                   1417.0           0
United Arab Emirates          9890318.0                9603499.0          15
Portugal                      9663542.0                9415073.0         297
...                                 ...                      ...         ...
Papua New Guinea               317150.0                 257566.0          43
Yemen                          643501.0                 404781.0          10
Chad                           282003.0                 153238.0           0
Haiti                          163710.0                 112335.0           7
Burundi                         10372.0                   9906.0           0

                      population       ratio
country
Gibraltar                33698.0  124.737373
Malta                   443646.0  106.760570
Niue                      1619.0  101.914762
United Arab Emirates  10051436.0   98.397065
Portugal              10150252.0   95.204947
...                          ...         ...
Papua New Guinea       9220306.0    3.439691
Yemen                 30882462.0    2.083710
Chad                  17203787.0    1.639191
Haiti                 11623799.0    1.408404
Burundi               12469663.0    0.083178

[197 rows x 9 columns]

In [10]:
df3 = df2[df2['ratio']<=100]
df3

,Unnamed: 0,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,New_deaths,population,ratio
country,,,,,,,,,
United Arab Emirates,30916,ARE,2022-03-29,24463702.0,9890318.0,9603499.0,15,10051436.0,98.397065
Portugal,24636,PRT,2022-03-10,22923599.0,9663542.0,9415073.0,297,10150252.0,95.204947
Cuba,7263,CUB,2022-03-27,35342367.0,10630665.0,9910237.0,98,11312548.0,93.972331
Chile,6318,CHL,2022-03-22,50302179.0,17859475.0,17346012.0,11447,19275294.0,92.654748
Brunei Darussalam,4562,BRN,2022-03-18,1068468.0,407945.0,404935.0,5,443903.0,91.899582
...,...,...,...,...,...,...,...,...,...
Papua New Guinea,23300,PNG,2022-03-28,574716.0,317150.0,257566.0,43,9220306.0,3.439691
Yemen,32488,YEM,2022-03-16,807502.0,643501.0,404781.0,10,30882462.0,2.083710
Chad,5884,TCD,2022-03-18,419469.0,282003.0,153238.0,0,17203787.0,1.639191
Haiti,12640,HTI,2022-03-23,249801.0,163710.0,112335.0,7,11623799.0,1.408404
Burundi,4798,BDI,2022-03-18,12166.0,10372.0,9906.0,0,12469663.0,0.083178

In [17]:
# top 10
top = df3.iloc[:10]['ratio'].mean()

# bottom 10
bottom = df3.iloc[-10:]['ratio'].mean()

print(top)
print(bottom)

round(top - bottom, 1)

91.81697544672711
3.4504083912453525

88.4

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32911 entries, 0 to 32910
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               32911 non-null  int64
 1   country                  32911 non-null  object
 2   iso_code                 32911 non-null  object
 3   date                     32911 non-null  object
 4   total_vaccinations       32911 non-null  float64
 5   people_vaccinated        32911 non-null  float64
 6   people_fully_vaccinated  32911 non-null  float64
 7   New_deaths               32911 non-null  int64
 8   population               32911 non-null  float64
 9   ratio                    32911 non-null  float64
dtypes: float64(5), int64(2), object(3)
memory usage: 2.5+ MB